### ISSUE TITLE
Tracker link 

### ISSUE THREAD

**Issue by shriramters** [hartwork/wnpp.debian.net#954]
![image](https://github.com/hartwork/wnpp.debian.net/assets/127589779/3a692f03-f289-4b59-838b-c449c98d425c)

Both of [these columns](https://github.com/hartwork/wnpp.debian.net/blob/67b24c56c33aeac0238962a0480339a5820b3d79/wnpp_debian_net/templates/wnpp_debian_net/debianwnpp_list.html#L287-L288) link to the same bug report page. Would it be a good idea to change the href on the project name to the tracker.debian.org page of that package?

**Comment by hartwork** [comment]
Hi @shriramters, for ITP and RFP there will not be a tracker package because there is no package yet. From the bug it takes two clicks to get to the tracker page, which is admittedly a bit much. I don't see a good way forward yet. Would making it point to the tracker only some of the time and to not be a link at all else be an improvement?

**Comment by shriramters** [comment]
> Would making it point to the tracker only some of the time and to not be a link at all else be an improvement

Yes I certainly think so, although it's just a suggestion. Please do as you deem fit.

**Comment by hartwork** [comment]
@shriramters I have implemented your suggestion in pull request #956 now and after deployment the change is now live and can be observed at e.g. https://wnpp.debian.net/?sort=project%2Fasc . Cheers :beers: :smiley:

**Comment by shriramters** [comment]
Thank you so much! I just checked it, this is really convenient
